export const ENDPOINTS = {
  saveGatewayConfig: '/admin/save_gateway_config',
  saveGatewayToolConfig: '/admin/save_gateway_tool_config',
  saveGatewayProtocol: '/admin/save_gateway_protocol',
  saveGatewayAuth: '/admin/save_gateway_auth',
  queryGatewayConfigList: '/admin/query_gateway_config_list',
  queryGatewayConfigPage: '/admin/query_gateway_config_page',
  queryGatewayToolList: '/admin/query_gateway_tool_list',
  queryGatewayToolPage: '/admin/query_gateway_tool_page',
  queryGatewayToolByGatewayId: '/admin/query_gateway_tool_list_by_gateway_id',
  deleteGatewayTool: '/admin/delete_gateway_tool_config',
  queryGatewayProtocolList: '/admin/query_gateway_protocol_list',
  queryGatewayProtocolPage: '/admin/query_gateway_protocol_page',
  queryGatewayProtocolByGatewayId: '/admin/query_gateway_protocol_list_by_gateway_id',
  deleteGatewayProtocol: '/admin/delete_gateway_protocol',
  queryGatewayAuthList: '/admin/query_gateway_auth_list',
  queryGatewayAuthPage: '/admin/query_gateway_auth_page',
  deleteGatewayAuth: '/admin/delete_gateway_auth',
  analysisProtocol: '/admin/analysis_protocol',
  importGatewayProtocol: '/admin/import_gateway_protocol',
  testCallGateway: '/admin/test_call_gateway',
} as const;